'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

export default function LoginPage() {
  const router = useRouter();
  const [isRegistering, setIsRegistering] = useState(false);
  
  // Login state
  const [identifier, setIdentifier] = useState(''); // username or phone
  
  // Registration state
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [username, setUsername] = useState(''); // autogenerated read-only
  const [phone, setPhone] = useState(''); // exactly 10 digits
  
  const [password, setPassword] = useState('');
  
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  // Auto-generate username whenever first or last name changes
  useEffect(() => {
    if (isRegistering) {
      const generated = (firstName.trim() + lastName.trim()).toLowerCase();
      setUsername(generated);
    }
  }, [firstName, lastName, isRegistering]);

  async function handleSubmit(e) {
    e.preventDefault();
    setError('');

    // Pre-flight validation for phone number
    if (isRegistering) {
      if (!/^\d{10}$/.test(phone)) {
        setError('Phone number must be exactly 10 digits.');
        return;
      }
      if (!username) {
        setError('First Name and Last Name are required to generate a Username.');
        return;
      }
    }

    setLoading(true);

    try {
      const endpoint = '/api/auth/login'; // single endpoint avoids Turbopack folder watcher bug
      const body = isRegistering 
        ? { action: 'register', first_name: firstName, last_name: lastName, username, phone_number: phone, password } 
        : { action: 'login', identifier, password };

      const res = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      const data = await res.json();

      if (res.ok) {
        router.push('/dashboard');
        router.refresh();
      } else {
        setError(data.error || (isRegistering ? 'Registration failed.' : 'Login failed. Please try again.'));
      }
    } catch (err) {
      console.error(err);
      setError('Could not connect to the server. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  function toggleMode() {
    setIsRegistering(!isRegistering);
    setError('');
    setIdentifier('');
    setFirstName('');
    setLastName('');
    setUsername('');
    setPhone('');
    setPassword('');
  }

  return (
    <div className="login-page">
      <div className="login-card">
        <div style={{ textAlign: 'center', marginBottom: '24px' }}>
          <img
            src="/companyLogo.jpg"
            alt="Sarthak Creations"
            width={179}
            height={90}
            style={{ width: '100%', maxWidth: '179px', height: 'auto', display: 'block', margin: '0 auto' }}
          />
          <h2 style={{ fontSize: '14px', color: 'var(--text-secondary)', marginTop: '8px', fontWeight: '500' }}>
            Order Management System — {isRegistering ? 'Register Account' : 'Sign In'}
          </h2>
        </div>

        {error && (
          <div className="banner banner-error" style={{ marginBottom: '16px' }}>
            {error}
          </div>
        )}

        <form className="login-form" onSubmit={handleSubmit}>
          {isRegistering ? (
            <>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="form-group">
                  <label className="form-label" htmlFor="reg-firstname">
                    First Name <span className="required">*</span>
                  </label>
                  <input
                    id="reg-firstname"
                    type="text"
                    className="form-input"
                    value={firstName}
                    onChange={(e) => setFirstName(e.target.value)}
                    placeholder="e.g. Aaditya"
                    required
                  />
                </div>
                <div className="form-group">
                  <label className="form-label" htmlFor="reg-lastname">
                    Last Name <span className="required">*</span>
                  </label>
                  <input
                    id="reg-lastname"
                    type="text"
                    className="form-input"
                    value={lastName}
                    onChange={(e) => setLastName(e.target.value)}
                    placeholder="e.g. Bhure"
                    required
                  />
                </div>
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="reg-username">
                  Username (Auto-Generated)
                </label>
                <input
                  id="reg-username"
                  type="text"
                  className="form-input"
                  value={username}
                  placeholder="firstname+lastname"
                  readOnly
                  style={{ backgroundColor: 'var(--bg-secondary)', cursor: 'not-allowed', color: 'var(--text-secondary)' }}
                />
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="reg-phone">
                  Phone Number (10 Digits) <span className="required">*</span>
                </label>
                <input
                  id="reg-phone"
                  type="text"
                  className="form-input"
                  value={phone}
                  onChange={(e) => {
                    const val = e.target.value.replace(/\D/g, '');
                    if (val.length <= 10) setPhone(val);
                  }}
                  placeholder="Enter 10 digit number"
                  required
                />
              </div>
            </>
          ) : (
            <div className="form-group">
              <label className="form-label" htmlFor="identifier">
                Username or Phone <span className="required">*</span>
              </label>
              <input
                id="identifier"
                type="text"
                className="form-input"
                value={identifier}
                onChange={(e) => setIdentifier(e.target.value)}
                placeholder="Enter username or 10-digit phone"
                required
              />
            </div>
          )}

          <div className="form-group">
            <label className="form-label" htmlFor="password">
              Password <span className="required">*</span>
            </label>
            <input
              id="password"
              type="password"
              className="form-input"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter password"
              required
            />
          </div>

          <button
            id="auth-submit"
            type="submit"
            className="btn btn-primary"
            disabled={loading}
            style={{ marginTop: '4px' }}
          >
            {loading ? (
              <><span className="spinner" /> {isRegistering ? 'Registering...' : 'Signing in...'}</>
            ) : (
              isRegistering ? 'Create Account' : 'Sign In'
            )}
          </button>
        </form>

        <div style={{ textAlign: 'center', marginTop: '16px', fontSize: '13px' }}>
          <button 
            type="button" 
            onClick={toggleMode} 
            className="btn-ghost" 
            style={{ color: 'var(--primary-color)', textDecoration: 'underline', padding: 0, border: 'none', background: 'none', cursor: 'pointer' }}
          >
            {isRegistering ? 'Already have an account? Sign In' : 'Need an account? Register'}
          </button>
        </div>
      </div>
    </div>
  );
}
